# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20171107_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_format', models.CharField(choices=[('vis', 'vis')], max_length=255)),
                ('content', models.FileField(upload_to='_files//%Y%m%d/json/')),
            ],
        ),
        migrations.AddField(
            model_name='textfile',
            name='status',
            field=models.CharField(choices=[('empty', 'empty'), ('pending', 'pending'), ('done', 'done')], default='empty', max_length=10),
        ),
        migrations.AlterField(
            model_name='textfile',
            name='content',
            field=models.FileField(upload_to='_files//%Y%m%d/'),
        ),
        migrations.AddField(
            model_name='jsonfile',
            name='text_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='json', to='profiles.TextFile'),
        ),
    ]
