# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 08:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20171116_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonfile',
            name='content',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
