# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20171116_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textfile',
            name='status',
        ),
        migrations.AddField(
            model_name='jsonfile',
            name='status',
            field=models.CharField(choices=[('empty', 'empty'), ('pending', 'pending'), ('done', 'done')], default='empty', max_length=10),
        ),
    ]
