# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20171121_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfile',
            name='minimized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jsonfile',
            name='json_format',
            field=models.CharField(choices=[('vis_factor', 'vis_factor'), ('vis_interaction', 'vis_interaction'), ('vis_resolution', 'vis_resolution'), ('raw', 'raw')], max_length=255),
        ),
    ]
